# Generated by Django 2.1.5 on 2019-01-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Createdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
